# Generated by Django 4.2.7 on 2023-12-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
